version: '2.2'
services:
  efitness:
    tty: true
    stdin_open: true
    cap_add:
      - SYS_PTRACE
    build: .
    restart: always
    ports:
      - "0.0.0.0:30077:30077"
    mem_limit: 512m
    cpus: 2